### ISSUE TITLE
Error when trying your sample BioQuery...

### ISSUE THREAD

**Issue by billylo1** [hourliert/graphql_client#13]
I am new to Dart... any hints on why?  thx. Billy.

On this line:  The IDE gives me a warning of Invalid Override.
  `OperationType get type => OperationType.query;`

At runtime:
`malformed type: line 93 pos 3: cannot resolve class 'OperationType' from 'ViewerBioQuery'
OperationType get type => OperationType.query;
^`

**Comment by hourliert** [comment]
Hi @billylo1,

Thanks for your interest in this project.
I have cloned the project from scratch and tester the example in the master branch and everything works out of the box for me. I have installed dart using brew by following this guide: [https://www.dartlang.org/install/mac](https://www.dartlang.org/install/mac).

To make the project works, you have to define a environnement variable `GITHUBQL_TOKEN=YOUR_PERSONAL_GITHUB_TOKEN_WITH_THE_GQL_RIGHT`. The official documentation is [here](https://developer.github.com/v4/guides/forming-calls/).

Let me know if you still have an issue. Otherwise, I will close this issue in one week.

Cheers!

**Comment by billylo1** [comment]
Perfect.  Thx!!
